### ISSUE TITLE
Build Action is Broken

### ISSUE THREAD

**Issue by BareGeek** [Nice-Keyboards/nice60-zmk-config#3]
The build workflow is currently broken.  It errors on both the version of CMake being too old and on the location of the file that is being used in the cat call under "Generated DTS file".  I changed runs-on: to ubuntu-latest, the image to zmkfirmware/zmk-build-arm:stable, and the DTS file statement to: 

run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

This allows it to build correctly.

**Comment by Nicell** [comment]
Thanks for bringing this up, I've upgraded the build system to the new way, which shouldn't break in the future.
